#!/bin/bash
if node --version; then 
    echo "Found NodeJS"
else
    echo "NodeJS not found"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    source ~/.bashrc
    nvm install node
fi

npm i -g yarn
yarn
